//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bodegas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bodegas()
        {
            this.detalles_movimientos = new HashSet<detalles_movimientos>();
            this.tipo_bodega_bodegas = new HashSet<tipo_bodega_bodegas>();
        }
    
        public int id_bodega { get; set; }
        public string nombre_bodega { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_tipo_bodega { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual sucursales sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_movimientos> detalles_movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_bodega_bodegas> tipo_bodega_bodegas { get; set; }
    }
}
