//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventarioEntities : DbContext
    {
        public inventarioEntities()
            : base("name=inventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora> bitacora { get; set; }
        public virtual DbSet<bodegas> bodegas { get; set; }
        public virtual DbSet<clasificacion> clasificacion { get; set; }
        public virtual DbSet<detalles_movimientos> detalles_movimientos { get; set; }
        public virtual DbSet<medidas_peso> medidas_peso { get; set; }
        public virtual DbSet<movimientos> movimientos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<proveedor_producto> proveedor_producto { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sub_clasificaciones> sub_clasificaciones { get; set; }
        public virtual DbSet<sucursales> sucursales { get; set; }
        public virtual DbSet<tipo_bodega> tipo_bodega { get; set; }
        public virtual DbSet<tipo_bodega_bodegas> tipo_bodega_bodegas { get; set; }
        public virtual DbSet<tipo_movimiento> tipo_movimiento { get; set; }
        public virtual DbSet<tipo_proveedor> tipo_proveedor { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<vigencia_promedio> vigencia_promedio { get; set; }
    }
}
