//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimientos()
        {
            this.bitacora = new HashSet<bitacora>();
            this.detalles_movimientos = new HashSet<detalles_movimientos>();
        }
    
        public int id_movimiento { get; set; }
        public int id_tipo_movimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> costo_total_con_iva { get; set; }
        public Nullable<decimal> costo_total_sin_iva { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_bodega_cargo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacora> bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_movimientos> detalles_movimientos { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual tipo_movimiento tipo_movimiento { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
