//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.detalles_movimientos = new HashSet<detalles_movimientos>();
            this.proveedor_producto = new HashSet<proveedor_producto>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_vigencia_promedio { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
        public Nullable<int> id_sub_clasificacion { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.TimeSpan> hora_creacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<decimal> costo_unitario_con_iva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_movimientos> detalles_movimientos { get; set; }
        public virtual sub_clasificaciones sub_clasificaciones { get; set; }
        public virtual vigencia_promedio vigencia_promedio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proveedor_producto> proveedor_producto { get; set; }
    }
}
